apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: master-ingress
  namespace: master-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "k8sbfr.zapto.org"
    http:
      paths:
      # - pathType: Prefix
      - path: /popote
        pathType: Prefix
        backend:
          namespace: popote 
          service:
            name: popote-service
            port: 
              number: 8080
