apiVersion: networking.k8s.io/v1
#apiVersion: v1
kind: Ingress
metadata:
  name: k8sbfr-ingress-kubwebview
spec:
  ingressClassName: nginx
  rules:
    # - host: k8sbfr.zapto.org
    - host: *
      http:
        paths:
          - path: /kubewebview
            pathType: Prefix
            backend:
              service:
                name: kube-web-view
                port: 
                  number: 80