
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: popote
  name: deployment-popote-monopod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-popote-monopod
  template:
    metadata:
      labels:
        app: deployment-popote-monopod
    spec:
      containers:
      - name: popote-mariadb
        image: fbruno/popote_vuejs_k8s-tags-10-mariadb:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3306
          
      - name: popote-backend
        image: fbruno/popote_vuejs_k8s-tags-10-backend:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
      
      - name: popote-frontend
        image: fbruno/popote_vuejs_k8s-tags-10-frontend:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
      
      # - name: popote-nginx
      #   image: fbruno/popote_vuejs_k8s-tags-10-nginx 
      #   resources:
      #     requests:
      #       memory: "64Mi"
      #       cpu: "250m"
      #     limits:
      #       memory: "128Mi"
      #       cpu: "500m"
      #   ports:
      #     - containerPort: 80
      #     - containerPort: 443

      restartPolicy: Always