apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-popote
  namespace: popote
spec:
  ingressClassName: nginx
  rules:
  - host: "k8sbfr.zapto.org/popote"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: popote-service
            port:
              number: 8080
