kind: Service
apiVersion: v1
metadata:
  name: popote-service
  labels:
    app: deployment-popote-monopod
  namespace: popote
spec:
  selector:
    app: deployment-popote-monopod
  ports:
  - name: popote-port
    port: 80
    targetPort: 80
  - name: popote-port-sec
    port: 443
    targetPort: 443
  - name: popote-port-backend
    port: 3000
    targetPort: 3000
  - name: popote-port-mariadb
    port: 3306
    targetPort: 3306
  type: ClusterIP
  