apiVersion: v1
kind: Service
metadata:
  name: popote-service
  labels:
    app: deployment-popote-monopod
  namespace: popote
spec:
  selector:
    app: deployment-popote-monopod
  type: LoadBalancer
  externalIPs:
  - 192.168.1.34
  ports:
  - name: http-port
    port: 8080
    targetPort: 80
  # - name: http1-port
  #   port: 8080
  #   targetPort: 8080
  # - name: https-port
  #   port: 443
  #   targetPort: 443
  # - name: backend-port
  #   port: 3000
  #   targetPort: 3000
  # - name: mariadb-port
  #   port: 3306
  #   targetPort: 3306
  