kind: Service
apiVersion: v1
metadata:
  name: popote-service
  labels:
    app: popote
  namespace: popote
spec:
  selector:
    app: popote
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443
    targetPort: 443
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
  