kind: Service
apiVersion: v1
metadata:
  name: popote-service
  labels:
    app: deployment-popote-monopod
  namespace: popote
spec:
  selector:
    app: deployment-popote-monopod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: popote-port
  - protocol: TCP
    port: 443
    targetPort: 443
    name: popote-port-sec
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: popote-port-backend
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: popote-port-mariadb
  type: ClusterIP
  