kind: Service
apiVersion: v1
metadata:
  name: monapp-service
  labels:
    app: monapp
spec:
  selector:
    app: monapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  