
apiVersion: apps/v
kind: Deployment
metadata:
  namespace: popote
  name: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  template:
    metadata:
      labels:
        app: deployment-backend
    spec:
      containers:
      - name: popote-backend
        #image: fbruno/popote_vuejs_k8s-tags-10-backend:latest
        image: fbruno/popote_vuejs_k8s-tags-11-backend:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000

      restartPolicy: Always
