apiVersion: v1
kind: Service
metadata:
  name: external-k8sbfr-hello-node
  namespace: k8sbfr-hello-node
spec:
  type: ExternalName
  externalName: k8sbfr-hello-node.k8sbfr-hello-node.svc.cluster.local
