#apiVersion: networking.k8s.io/v1
apiVersion: v1
kind: Ingress
metadata:
  name: k8sbfr-ingress-hello-node
  # namespace: k8sbfr-hello-node
spec:
  ingressClassName: k8sbfr-nginx
  rules:
    # - host: 
    #   - k8sbfr.zapto.org
    #   - localhost
    - http:
      paths:
        - path: /hello
          pathType: Prefix
          backend:
            service:
              #name: external-k8sbfr-hello-node
              name: k8sbfr-hello-node
              port: 
                number: 8080
