apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8sbfr-ingress-hello-node
  #namespace: k8sbfr-hello-node
  namespace: ingress-nginx
spec:
  rules:
    - host: k8sbfr.zapto.org
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: services/k8sbfr-hello-node
                port: 8080
