apiVersion: v1
kind: Service
metadata:
  name: k8sbfr-hello-node
  namespace: k8sbfr-hello-node
spec:
  # externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: k8sbfr-hello-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

kind: Service
  metadata:
    name: external-k8s-hello-node
  spec:
    type: ExternalName
    externalName: k8sbfr-hello-node.k8sbfr-hello-node.svc.cluster.local