apiVersion: v1
kind: Service
metadata:
  name: k8sbfr-hello-node
  namespace: k8sbfr-hello-node
spec:
  # externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: k8sbfr-hello-node
  ports:
    #- protocol: TCP
    - protocol: TCP
      port: 8080
      targetPort: 80

