apiVersion: v1
kind: Service
metadata:
  name: k8sbfr-hello-node
  namespace: k8sbfr-hello-node
spec:
  selector:
    app: k8sbfr-hello-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080