apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      labels:
        app: monapp
    spec:
      containers:
        - image: artefacts.sa-cim.local/monapp:0.1
          name: monapp
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          command: ["gunicorn"]
          args: ["--bind","0.0.0.0:5000","mainapp:app"]
          volumeMounts:
          - mountPath: /app/static
            name: static
        - image: nginx:1.21-alpine
          name: nginx
          ports:
            - containerPort: 443
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: conf
          - mountPath: /app/static
            name: static

      volumes:
      - name: conf
        configMap:
          name: monapp-nginx
      - name: static
        emptyDir: {}