apiVersion: v1
kind: Service
metadata:
  name: k8sbfr-loadbalancer-service
spec:
  selector:
    app: k8sbfr-app
  ports:
    - port: 8765
      targetPort: 9376
  externalTrafficPolicy: Local
  type: LoadBalancer