apiVersion: v1
kind: Service
metadata:
  name: bfrk8s-nginx
  labels:
    run: bfrk8s-nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: bfrk8s-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfrk8s-nginx
spec:
  selector:
    matchLabels:
      run: bfrk8s-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: k8sbfr-nginx
    spec:
      volumes:
      - name: k8sbfr-secret-volume
        secret:
          secretName: k8sbfr-nginxsecret
      - name: k8sbfr-configmap-volume
        configMap:
          name: k8sbfr-nginxconfigmap
      containers:
      - name: k8sbfr-nginxhttps
        image: soltest4hpvsop/nginxhttps
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: k8sbfr-secret-volume
        - mountPath: /etc/nginx/conf.d
          name: k8sbfr-configmap-volume
