apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sbfr-nginx
spec:
  selector:
    matchLabels:
      run: k8sbfr-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: k8sbfr-nginx
    spec:
      containers:
      - name: k8sbfr-nginx
        image: nginx
        ports:
        - containerPort: 80

